# Generated by Django 4.1.7 on 2023-03-13 16:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("articles", "0002_alter_article_url"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="article",
            name="subtheme_id",
        ),
        migrations.AddField(
            model_name="article",
            name="subthemes",
            field=models.ManyToManyField(to="articles.subtheme"),
        ),
    ]
